<%@ Page Title="Upcoming Events" Language="C#" MasterPageFile="~/Home.master" AutoEventWireup="true" CodeFile="Post_Upcoming_Events.aspx.cs" Inherits="Post_Upcoming_Events" %>

<%-- Add content controls here --%>
<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="asp" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">


    
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<div class="wrap-title-page">
					<div class="container">
						<div class="row">
							<div class="col-xs-12"><h1 class="ui-title-page">Upcoming Events<asp:ToolkitScriptManager ID="ToolkitScriptManager1"  runat="server">
            </asp:ToolkitScriptManager></h1></div>
						</div>
					</div><!-- end container-->
				</div><!-- end wrap-title-page -->


				<div class="section-breadcrumb">
					<div class="container">
						<div class="row">
							<div class="col-xs-12">
								<div class="wrap-breadcrumb clearfix">
									<ol class="breadcrumb">
										<li><a href="javascript:void(0);"><i class="icon stroke icon-House"></i></a></li>
										<li class="active">Upcoming Events</li>
									</ol>
								</div>
							</div>
						</div><!-- end row -->
					</div><!-- end container -->
				</div><!-- end section-breadcrumb -->
    
     <section >
      <div class="container">
         <div class="section-content">
             <div class="row">
                 <div class="col-md-12">
                    <h2 class="ui-title-block">Upcoming <strong>Events</strong></h2>
                    <h4><asp:Label runat="server" ID="lbl_user" ForeColor="Maroon"></asp:Label></h4>
                 </div>
             </div>
         </div>
      </div>
    </section>
<div class="page-title bgg">
    <div class="container clearfix">
        <div class="title-area pull-left">
            <h2><span style="color:#3ca1db;"></span></h2>
        </div><!-- /.pull-right -->
    </div>
</div><!-- end page-title -->
<section class="section bgw">
            <div class="container">
                <div class="section-title-2 text-center">

<table width="100%">
    
    <tr>
        <td align="left">
            Event ID :</td>
        <td align="left" style="padding:5px;">
            <asp:Label ID="lbl_Id" runat="server" Font-Bold="True"></asp:Label>
        </td>
    </tr>
    <tr>
        <td align="left">
            Event Date : </td>
        <td align="left" style="padding:5px;">
            <asp:TextBox ID="txtDisplayDate" runat="server" BorderStyle="Dashed" BorderWidth="1" 
                Width="220px"></asp:TextBox>
            
            <asp:FilteredTextBoxExtender ID="txtDisplayDate_FilteredTextBoxExtender" 
                runat="server" Enabled="True" ValidChars="0123456789/" TargetControlID="txtDisplayDate">
            </asp:FilteredTextBoxExtender>
            
            <asp:CalendarExtender ID="txtDisplayDate_CalendarExtender" runat="server" 
                Enabled="True" TargetControlID="txtDisplayDate" Format="dd/MM/yyyy">
            </asp:CalendarExtender>
            
        </td>
    </tr>
    <tr>
        <td align="left">
            Events Title :</td>
        <td align="left" style="padding:5px;">
            <asp:TextBox ID="txt_News_Title" runat="server" BorderStyle="Dashed" BorderWidth="1" 
                Width="500px"></asp:TextBox>
        </td>
    </tr>
    <tr>
        <td align="left">
            
            </td>
        <td align="left" style="padding:5px;">
            <asp:ImageButton ID="btn_Save" runat="server" 
                ImageUrl="~/Images/tour_save_button.png" onclick="btn_Save_Click" />
        &nbsp; &nbsp; &nbsp; &nbsp; 
            <asp:ImageButton ID="ImageButton1" runat="server" ImageUrl="~/Images/back.jpg" 
                onclick="ImageButton1_Click" />
        </td>
    </tr>
    <tr>
        <td colspan="2" align="center">
            
            <asp:Label ID="lblInfo" runat="server" Font-Bold="True" Font-Italic="False" 
                ForeColor="#CC3300"></asp:Label>
        </td>
    </tr>
    <tr>
        <td colspan="2" align="left"><h4>Existing Events</h4> </td>
    </tr>
    <tr>
        <td colspan="2" align="left" style="line-height:3em;">
            
            <asp:GridView ID="news_Grid" runat="server" AllowPaging="True" AutoGenerateColumns="False"
                AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" CellPadding="4"
                DataSourceID="AccessDataSource1" ForeColor="#333333" GridLines="None" 
                Width="100%" OnSelectedIndexChanged="news_Grid_SelectedIndexChanged" 
                OnRowDeleting="news_Grid_RowDeleting" style="left: 1px; top: -4px" >
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <Columns>
                    <asp:BoundField DataField="ID" HeaderText="ID" SortExpression="ID" />
                    <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
                    <asp:BoundField DataField="Event" HeaderText="Title" SortExpression="Title" />
                </Columns>
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" Font-Size="9pt" HorizontalAlign="Left" VerticalAlign="Top" />
                <EditRowStyle BackColor="#999999" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" Font-Size="10pt" HorizontalAlign="Left" />
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            </asp:GridView>
            <asp:AccessDataSource ID="AccessDataSource1" runat="server" 
                DataFile="~/App_Data/cDatabase.mdb"                 
                SelectCommand="SELECT [ID] as [ID], [Event_date] as [Date], [Event_Title] as [Event] FROM [tbl_upcoming_events] ORDER BY [ID] DESC">
            </asp:AccessDataSource>
          </td>
    </tr>
    <tr>
        <td align="left" 
            colspan="2" align="left">
            
            &nbsp;</td>
    </tr>
</table>
                </div>
            </div>
</section>

    

    </asp:Content>