<%@ Page Language="C#" MasterPageFile="~/Admin.master" AutoEventWireup="true" CodeFile="Post-Latest-News.aspx.cs" Inherits="update_news" Title="Update News" %>

<%@ Register assembly="AjaxControlToolkit" namespace="AjaxControlToolkit" tagprefix="asp" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    
    <h5>Latest News</h5>
    
<section class="section bgw">
            <div class="container">
                <div class="section-title-2 text-center">
<table width="100%">
    <tr>
        <td align="left">
            News ID</td>
        <td align="left" style="padding:5px;">
            <asp:Label ID="lbl_Id" runat="server" Font-Bold="True"></asp:Label>
            <asp:ToolkitScriptManager ID="ToolkitScriptManager1" runat="server">
            </asp:ToolkitScriptManager>
        </td>
    </tr>
    <tr>
        <td align="left">
            News Date : </td>
        <td align="left" style="padding:5px;">
            <asp:TextBox ID="txtDisplayDate" runat="server" BorderStyle="Dashed" BorderWidth="1"
                Width="220px"></asp:TextBox>
            
            <asp:FilteredTextBoxExtender ID="txtDisplayDate_FilteredTextBoxExtender" 
                runat="server" Enabled="True" ValidChars="0123456789/" TargetControlID="txtDisplayDate">
            </asp:FilteredTextBoxExtender>
            
            <asp:CalendarExtender ID="txtDisplayDate_CalendarExtender" runat="server" 
                Enabled="True" TargetControlID="txtDisplayDate" Format="dd/MM/yyyy">
            </asp:CalendarExtender>
            
        </td>
    </tr>
    <tr>
        <td align="left">
            News Title :</td>
        <td align="left" style="padding:5px;">
            <asp:TextBox ID="txt_News_Title" runat="server" BorderStyle="Dashed" BorderWidth="1"
                Width="500px" Height="50px" TextMode="MultiLine"></asp:TextBox>
        </td>
    </tr>
    
    <tr>
        <td align="left">           
            Link :</td>
        <td align="left" style="padding:5px;">
              <asp:RadioButton ID="rbFile" runat="server" Text="File " AutoPostBack="True" Font-Bold="True" Font-Size="9pt" GroupName="link" OnCheckedChanged="rbFile_CheckedChanged" />
              &nbsp; &nbsp; &nbsp; &nbsp; 
              <asp:RadioButton ID="rbURL" runat="server" Text="URL" AutoPostBack="True" Font-Bold="True" OnCheckedChanged="rbLink_CheckedChanged" Font-Size="9pt" GroupName="link" />
              &nbsp; &nbsp; &nbsp; &nbsp; 
              <asp:RadioButton ID="rbNot" runat="server" Text="Not Applicable" 
                  AutoPostBack="True" Font-Bold="True" OnCheckedChanged="rbNot_CheckedChanged" 
                  Font-Size="9pt" GroupName="link" />
        </td>
    </tr>
    <tr>
        <td align="left">
            
            <asp:Label ID="lblFilePath" runat="server" Visible="False">File :</asp:Label>
        </td>
        <td align="left" style="padding:5px;">
            <asp:FileUpload ID="FileUpload1" runat="server"
                Visible="False" />
            &nbsp;<asp:CheckBox ID="chk_new" runat="server" AutoPostBack="True" 
                oncheckedchanged="chk_new_CheckedChanged" Text="Upload New File" 
                Visible="False" />
&nbsp;<asp:Label ID="Label1" runat="server" Text="0"></asp:Label>
        </td>
    </tr>
    <tr>
        <td align="left">
            
            <asp:Label ID="lblUrl" runat="server" Font-Bold="True" Visible="False">Url :</asp:Label>
        </td>
        <td align="left" style="padding:5px;">
            <asp:TextBox ID="txtURL" runat="server" BorderStyle="Dashed" BorderWidth="1" Width="500px" 
                Visible="False">http://</asp:TextBox>
        </td>
    </tr>
    <tr>
        <td align="left" 
            class="style2">
            
            </td>
        <td align="left" style="padding:5px;">
            <asp:ImageButton ID="btn_Save" runat="server" 
                ImageUrl="~/Images/tour_save_button.png" onclick="btn_Save_Click" />
        &nbsp; &nbsp; &nbsp; &nbsp; 
            <asp:ImageButton ID="ImageButton1" runat="server" ImageUrl="~/Images/back.jpg" 
                onclick="ImageButton1_Click" />
        </td>
    </tr>
    <tr>
        <td colspan="2" align="center">
            
            <asp:Label ID="lblInfo" runat="server" Font-Bold="True" Font-Italic="False" 
                ForeColor="#CC3300"></asp:Label>
        </td>
    </tr>
    <tr>
        <td colspan="2" align="left"><h4>Existing News</h4> </td>
    </tr>
    <tr>
        <td colspan="2" align="left" style="line-height:3em;">
            <asp:GridView ID="news_Grid" runat="server" AutoGenerateColumns="False"
                AutoGenerateDeleteButton="True" AutoGenerateSelectButton="True" CellPadding="4"
                DataSourceID="AccessDataSource1" ForeColor="#333333" GridLines="None" 
                Width="100%" OnSelectedIndexChanged="news_Grid_SelectedIndexChanged" 
                OnRowDeleting="news_Grid_RowDeleting" style="left: 1px; top: -4px" >
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <Columns>
                    <asp:BoundField DataField="ID" HeaderText="ID" SortExpression="ID" />
                    <asp:BoundField DataField="Date" HeaderText="Date" SortExpression="Date" />
                    <asp:BoundField DataField="Title" HeaderText="Title" SortExpression="Title" />
                    <asp:BoundField DataField="File_path" HeaderText="File_path" 
                        SortExpression="File_path" />
                    <asp:BoundField DataField="Link" HeaderText="Link" SortExpression="Link" />
                    <asp:BoundField DataField="Link_type" HeaderText="Link_type" 
                        SortExpression="Link_type" />
                </Columns>
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" Font-Size="9pt" HorizontalAlign="Left" VerticalAlign="Top" />
                <EditRowStyle BackColor="#999999" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" Font-Size="10pt" HorizontalAlign="Left" />
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
            </asp:GridView>
            <asp:AccessDataSource ID="AccessDataSource1" runat="server" 
                DataFile="~/App_Data/cDatabase.mdb" 
                SelectCommand="SELECT [news_Id] as [ID], [news_Date] as [Date], [news_Title] as [Title], [news_filepath] as [File_path], [news_Link] as [Link], [news_LinkType] as [Link_type] FROM [tbl_news] ORDER BY [news_Id] DESC">
            </asp:AccessDataSource>
          </td>
    </tr>
    <tr>
        <td align="left" 
            colspan="2" align="left">
            
            &nbsp;</td>
    </tr>
</table>
                </div>
            </div>
</section>


    

</asp:Content>

